name: hello world

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build app
        run: echo "build app"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test app
        run: echo "test app"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy app
        run: echo "deploy app"
