name: hello world

on: workflow_dispatch

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello step
        run: |
          echo "this is hello world"
          echo "this is very important program"
